// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: types/ptypes.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AggregateDistanceService_DistanceAggregator_FullMethodName = "/AggregateDistanceService/DistanceAggregator"
)

// AggregateDistanceServiceClient is the client API for AggregateDistanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AggregateDistanceServiceClient interface {
	DistanceAggregator(ctx context.Context, in *AggregateDistanceRequest, opts ...grpc.CallOption) (*None, error)
}

type aggregateDistanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregateDistanceServiceClient(cc grpc.ClientConnInterface) AggregateDistanceServiceClient {
	return &aggregateDistanceServiceClient{cc}
}

func (c *aggregateDistanceServiceClient) DistanceAggregator(ctx context.Context, in *AggregateDistanceRequest, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, AggregateDistanceService_DistanceAggregator_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregateDistanceServiceServer is the server API for AggregateDistanceService service.
// All implementations must embed UnimplementedAggregateDistanceServiceServer
// for forward compatibility
type AggregateDistanceServiceServer interface {
	DistanceAggregator(context.Context, *AggregateDistanceRequest) (*None, error)
	mustEmbedUnimplementedAggregateDistanceServiceServer()
}

// UnimplementedAggregateDistanceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAggregateDistanceServiceServer struct {
}

func (UnimplementedAggregateDistanceServiceServer) DistanceAggregator(context.Context, *AggregateDistanceRequest) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistanceAggregator not implemented")
}
func (UnimplementedAggregateDistanceServiceServer) mustEmbedUnimplementedAggregateDistanceServiceServer() {
}

// UnsafeAggregateDistanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggregateDistanceServiceServer will
// result in compilation errors.
type UnsafeAggregateDistanceServiceServer interface {
	mustEmbedUnimplementedAggregateDistanceServiceServer()
}

func RegisterAggregateDistanceServiceServer(s grpc.ServiceRegistrar, srv AggregateDistanceServiceServer) {
	s.RegisterService(&AggregateDistanceService_ServiceDesc, srv)
}

func _AggregateDistanceService_DistanceAggregator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateDistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateDistanceServiceServer).DistanceAggregator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregateDistanceService_DistanceAggregator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateDistanceServiceServer).DistanceAggregator(ctx, req.(*AggregateDistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AggregateDistanceService_ServiceDesc is the grpc.ServiceDesc for AggregateDistanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AggregateDistanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AggregateDistanceService",
	HandlerType: (*AggregateDistanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DistanceAggregator",
			Handler:    _AggregateDistanceService_DistanceAggregator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types/ptypes.proto",
}
